name: macOS build

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: brew install upx

      - name: Cache
        id: cache-libraries
        uses: actions/cache@v2
        with:
          path: |
            libraries/depot_tools
            libraries/gn
            libraries/glad
            libraries/glfw
            libraries/skia
            libraries/v8
            libraries/libuv
          key: ${{ runner.os }}-build-cache-${{ hashFiles('.gclient', 'libraries/build_skia.sh', 'libraries/skia-args-mac.gn') }}

      - name: Sync
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: |
          source libraries/setup_build_env.sh
          libraries/sync.sh

      - name: Build Skia
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: |
          source libraries/setup_build_env.sh
          libraries/build_skia.sh

      - name: Build v8
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: |
          source libraries/setup_build_env.sh
          libraries/build_v8.sh

      - name: Build
        run: |
          source libraries/setup_build_env.sh
          cmake -S. -B out -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build out
          strip out/src/windowjs

      - name: Binary size
        run: |
          echo "Binary size after build:"
          stat -f%z out/src/windowjs
          upx -9 out/src/windowjs
          echo "Binary size after upx:"
          stat -f%z out/src/windowjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windowjs
          path: out/src/windowjs
